name: Push Workflow- Elastic Synthetics
on:
  push:
    branches: [main, master]
jobs:   
  test:
    env:
      ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
      ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
      EXAMPLE_OAUTH2_ENPOINT: ${{ secrets.EXAMPLE_OAUTH2_ENPOINT }}
      EXAMPLE_ACCESS_TOKEN: ${{ secrets.EXAMPLE_ACCESS_TOKEN }}
      EXAMPLE_CLIENT_ID: ${{ secrets.EXAMPLE_CLIENT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run ci-test
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/junit-*.xml'
          check_name: Elastic Synthetics Tests
  push:
    env:
      ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
      ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
      EXAMPLE_OAUTH2_ENPOINT: ${{ secrets.EXAMPLE_OAUTH2_ENPOINT }}
      EXAMPLE_ACCESS_TOKEN: ${{ secrets.EXAMPLE_ACCESS_TOKEN }}
      EXAMPLE_CLIENT_ID: ${{ secrets.EXAMPLE_CLIENT_ID }}
      SYNTHETICS_API_KEY: ${{ secrets.SYNTHETICS_API_KEY }}
    needs: test
    defaults:
      run:
        working-directory: ./apps/synthetics-replicator-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run push